Montaniarzii/Controllers/AttractionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Montaniarzii.BusinessLogic.Implementation;
using Montaniarzii.Code.Base;
using Montaniarzii.Common.DTOs;
using Montaniarzii.Entities.Entities;

namespace Montaniarzii.Controllers
{
    [Authorize]
    public class AttractionController : BaseController
    {
        private readonly AttractionService Service;
        public AttractionController(ControllerDependencies dependencies, AttractionService service) : base(dependencies)
        {
            Service = service;
        }

        [HttpGet]
        public async Task<IActionResult> GetNameOfAttractionsByPartiallyName(string partOfName)
        {

            if (partOfName != null && partOfName.Length >= 3)
            {
                return Ok(await Service.GetAllAttractionsByPartiallyName(partOfName));
            }
            else
            {
                return Ok(new List<GuidSelectListItemModel<Attraction>>());
            }

        }

        [HttpGet]
        public async Task<IActionResult> GetAllAttractionsWithCoordinatesByPartiallyName(string partOfName)
        {
            if (partOfName != null && partOfName.Length >= 3)
            {
                return Ok(await Service.GetAllAttractionsWithCoordinatesByPartiallyName(partOfName));
            }
            else
            {
                return Ok();
            }
        }

        [HttpGet]
        public async Task<IActionResult> GetAllAttractions(int count = 0)
        {
            var attractions = await Service.GetAllAttractions(count);

            return View(attractions);
        }

        [HttpGet]
        public async Task<IActionResult> GetAllAttractionsPaged(int count = 1)
        {
            var attractions = await Service.GetAllAttractions(count);

            return Ok(attractions);
        }

        [HttpGet]
        public async Task<IActionResult> GetAttractionInformation(Guid attractionId)
        {
            var attraction = await Service.GetAttractionInformation(attractionId);

            return View(attraction);
        }

        [HttpGet]
        public async Task<IActionResult> GetNameOfAttractionsPagedByPartiallyName(string partOfName, int count = 0)
        {
            if(partOfName.Length >= 3)
            {
                var attractions = await Service.GetAllAttractionsPagedByPartiallyName(partOfName, count);

                return Ok(attractions);
            }

            else
            {
                return Ok();
            }
            
        }

        [HttpGet]
        public async Task<IActionResult> GeAllMountains()
        {
            var mountains = await Service.GeAllMountains();

            return Ok(mountains);
        }

        [HttpGet]
        public async Task<IActionResult> GetAttractionsPagedFilteredByMountains(string mountains, int count = 0)
        {
            var attractions = await Service.GetAttractionsPagedFilteredByMountains(mountains, count);

            return Ok(attractions);
        }

        [HttpGet]
        public async Task<IActionResult> GetAllAttractionsPagedFilteredByPartiallyNameAndMountains(string partOfName, string mountains, int count = 0)
        {
            var attractions = await Service.GetAllAttractionsPagedFilteredByPartiallyNameAndMountains(partOfName, mountains, count);

            return Ok(attractions);
        }

        [HttpGet]
        public async Task<IActionResult> GetAllAttractionsPagedFilteredByPartiallyNameMountainsAndHeight(string partOfName, string mountains, int height, int count = 0)
        {
            var attractions = await Service.GetAllAttractionsPagedFilteredByPartiallyNameMountainsAndHeight(partOfName, mountains, height, count);

            return Ok(attractions);
        }

        [HttpGet]
        public async Task<IActionResult> GetTrendingAttractions()
        {
            return Ok(await Service.GetTrendingAttractions());
        }

        [HttpGet]
        public async Task<IActionResult> GetMaxHeightOfAttraction()
        {
            return Ok(await Service.GetMaxHeightOfAttraction());
        }

        [HttpGet]
        public async Task<IActionResult> GetMinHeightOfAttraction()
        {
            return Ok(await Service.GetMinHeightOfAttraction());
        }

        [HttpGet]
        public async Task<IActionResult> GetAllAttractionsPagedFilteredByPartiallyNameMountainsHeightAndLocation(string partOfName, string mountains, int height, string location, int count = 0)
        {
            var attractions = await Service.GetAllAttractionsPagedFilteredByPartiallyNameMountainsHeightAndLocation(partOfName, mountains, height, location, count);

            return Ok(attractions);
        }
    }
}

Montaniarzii/Controllers/TrainStationController.cs
using Microsoft.AspNetCore.Mvc;
using Montaniarzii.BusinessLogic.Implementation;
using Montaniarzii.Code.Base;

namespace Montaniarzii.Controllers
{
    public class TrainStationController : BaseController
    {
        private readonly TrainStationService Service;
        public TrainStationController(ControllerDependencies dependencies, TrainStationService service) : base(dependencies)
        {
            Service = service;
        }

        [HttpGet]
        public async Task<IActionResult> GetClosestTrainStationsPaged(Guid attractionId, int count = 0)
        {
            var trainStations = await Service.GetClosestTrainsStationsPaged(attractionId, count);

            return Ok(trainStations);
        }

        [HttpGet]
        public IActionResult GetViewForSearchingClosestsTrainStations()
        {
            return View();
        }




    }
}

Montaniarzii/Controllers/TripController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Montaniarzii.BusinessLogic.Implementation;
using Montaniarzii.BusinessLogic.Implementation.Trips.Models;
using Montaniarzii.Code.Base;
using Montaniarzii.Common.Exceptions;
using Montaniarzii.Entities.Enums;

namespace Montaniarzii.Controllers
{
    [Authorize]
    public class TripController : BaseController
    {
        private readonly TripService TripService;
        private readonly FollowService FollowService; 

        public TripController(ControllerDependencies dependencies, TripService tripService, FollowService followService) : base(dependencies)
        {
            TripService = tripService;
            FollowService = followService;
        }

        [HttpGet]
        public async Task<IActionResult> GetAllTrips(Guid userId)
        {
            var trips = await TripService.GetAllTripsView(userId);

            return View(trips);
        }

        [HttpGet]
        public IActionResult CreateTrip()
        {
            //var enumVal = Enum.GetValues(typeof(PostTypes)).Cast<PostTypes>;

            var model = new CreateTripModel();

            return View("CreateTrip", model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateTrip([FromBody]CreateTripModel model)
        {
            if (model == null)
            {
                throw new BadRequestErrorException();
            }

            await TripService.CreateTrip(model);

            return Ok();
        }

        //[HttpGet]
        //public IActionResult EditTrip()
        //{
        //    var model = TripService.EditTrip();

        //    return View(model);
        //}

        [HttpGet]
        public async Task<IActionResult> GetAllTripsForAListOfUsers(int count = 0)
        {
            var usersId = await FollowService.GetIdOfPeopleYouFollow();
            var trips = await TripService.GetAllTripsViewForAListOfUsers(usersId, count);

            return View(trips);  
        }

        [HttpGet]
        public async Task<IActionResult> GetAllTripsPagedForAListOfUsers(int count = 0)
        {
            var usersId = await FollowService.GetIdOfPeopleYouFollow();
            var trips = await TripService.GetAllTripsViewForAListOfUsers(usersId, count);

            return Ok(trips);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteTrip(Guid tripId)
        {
            await TripService.DeleteTrip(tripId);

            return Ok();
        }

        [HttpGet]
        public async Task<IActionResult> GetUpcomingEvents()
        {
            var events = await TripService.GetUpcomingEvents();

            return Ok(events); 
        }

        [HttpGet]
        public async Task<IActionResult> GetPastEvents()
        {
            var events = await TripService.GetPastEvents();

            return Ok(events);
        }
    }
}

Montaniarzii/Controllers/WarningController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Montaniarzii.BusinessLogic.Implementation;
using Montaniarzii.BusinessLogic.Implementation.Warnings.Models;
using Montaniarzii.Code.Base;

namespace Montaniarzii.Controllers
{
    [Authorize]
    public class WarningController : BaseController
    {
        private readonly WarningService Service;
        public WarningController(ControllerDependencies dependencies, WarningService service) : base(dependencies)
        {
            Service = service;
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult CreateWarning()
        {
            var model = new CreateWarningModel();

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> CreateWarning(CreateWarningModel model)
        {
            await Service.CreateWarning(model);

            return RedirectToAction("GetWarningsAsAdmin");
        }

        [HttpGet]
        public async Task<IActionResult> GetActiveWarningsAsUser()
        {
            return Ok(await Service.GetActiveWarningsAsUser());
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> GetWarningsAsAdmin(int count = 0)
        {
            var warnings = await Service.GetWarningsAsAdmin(count);

            return View(warnings);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteWarning(Guid warningId)
        {
            await Service.DeleteWarning(warningId);

            return RedirectToAction("GetWarningsAsAdmin");
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> UpdateWarning(Guid warningId)
        {
            var warning = await Service.GetUpdateWarning(warningId);

            return View(warning);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> UpdateWarning(UpdateWarningModel model)
        {
            await Service.UpdateWaning(model);

            return RedirectToAction("GetWarningsAsAdmin");
        }

    }
}

Montaniarzii/Views/Shared/Error_InternalServerError.cshtml
@model ErrorViewModel
@{
    ViewData["Title"] = "Error";
}

<h1 class="text-danger">Error 500</h1>
<h2 class="text-danger">An error occurred while processing your request.</h2>

Montaniarzii/Views/Shared/Error_NotFound.cshtml
@model ErrorViewModel
@{
    ViewData["Title"] = "Error";
}

<h1 class="text-danger">Error 404</h1>
<h2 class="text-danger">An error occurred while processing your request.</h2>

Montaniarzii/Views/Shared/Error_Unauthorized.cshtml
@model ErrorViewModel
@{
    ViewData["Title"] = "Error";
}

<h1 class="text-danger">Error 301</h1>
<h2 class="text-danger">An error occurred while processing your request.</h2>

Montaniarzii/Views/Shared/_Layout.cshtml
@inject Montaniarzii.Common.DTOs.CurrentUserDto CurrentUser

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-16" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Montaniarzii</title>
    @RenderSection("Styles", false)
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Montaniarzii.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Layout.css" />
     <link rel="stylesheet" href="https://unpkg.com/leaflet@1.8.0/dist/leaflet.css"
   integrity="sha512-hoalWLoI8r4UszCkZ5kL8vayOGVae1oxXe/2A4AO6J9+580uKHDO3JdHb7NzwwzK5xr/Fs0W40kiNHxM9vyTtQ=="
   crossorigin=""/>
   
<link rel="stylesheet" href="https://unpkg.com/leaflet-trails@0.0.1/leaflet-trails.css">
   

    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://kit.fontawesome.com/cc2b905796.js" crossorigin="anonymous"></script>
</head>
<body class="home-body">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                Montaniers
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">


                        @if (CurrentUser.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Attraction" asp-action="GetAllAttractions">Attractions</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Trip" asp-action="GetAllTripsForAListOfUsers">Feed</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="TrainStation" asp-action="GetViewForSearchingClosestsTrainStations">Train Station</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="UserAccount" asp-action="GetManagePage">Manage</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Trip" asp-action="CreateTrip">
                                    <i class="fa-solid fa-circle-plus"></i>Trip
                                </a>
                            </li>
                            if (CurrentUser.Role == "Admin")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="UserAccount" asp-action="GetAllUsers">Users</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Warning" asp-action="GetWarningsAsAdmin">Warning</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="SuggestionAttraction" asp-action="GetAllSuggestionAttractions">Suggestion</a>
                                </li>
                            }

                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                        }

                    </ul>
                </div>
                @if (CurrentUser.IsAuthenticated)
                {

                    <div class="search-box">
                        <div class="search-input">
                            <input type="text" class="form-control rounded-pill" placeholder="Search users" id="search-community">

                            <div id="suggestions-list">
                            </div>
                        </div>
                        <button type="button" class="btn btn-primary rounded-pill" id="search-button">Search</button>
                    </div>
                }
                <div>
                    @if (CurrentUser.IsAuthenticated)
                    {
                        <div style="display:flex;">
                        <button tabindex="0" type="button" class="btn btn-secondary" data-bs-container="body" data-bs-toggle="popover" data-bs-trigger="focus" data-bs-placement="bottom" data-bs-content="Bottom popover">
                            <i class="bi bi-bell"></i>
                        </button>
                        <div class="rounded-circle" style="margin-left:75px; background-image:url('/@CurrentUser.PhotoId/@CurrentUser.PhotoPath'); background-size:cover; width:40px; height:40px;overflow:hidden;">
                        </div>
                        <a class="text-decoration-none" style="margin-top:8px;" asp-controller="UserAccount" asp-action="GetProfilePage" asp-route-userId="@CurrentUser.Id">@CurrentUser.Username</a>
                        <a class="btn btn-primary rounded-pill" asp-controller="UserAccount" asp-action="Logout">Log out</a>
                        </div>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Montaniarzii - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
     <script src="https://unpkg.com/leaflet@1.8.0/dist/leaflet.js" integrity="sha512-BB3hKbKWOc9Ez/TAwyWxNXeoV9c1v6FIeYiBieIWkpLjauysF18NzgR1MBNBXf8/KABdlkX68nAhlwcDFLGPCQ=="crossorigin=""></script>
   <script src="https://unpkg.com/leaflet-trails@0.0.1/leaflet-trails.js"></script>
   <script src="https://unpkg.com/leaflet-simple-map-screenshoter"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.3.4/html2canvas.min.js"></script>
     <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/Layout.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>